XPATH_ESTATE_BUTTON = '//div[@class="mat-ripple block"]'
APPLICANT_DATA_NAV_ID = 'cdk-step-label-0-1'
XPATH_NEXT_BUTTON = '//button[@class="mat-focus-indicator mat-stepper-next mat-raised-button mat-button-base mat-primary"]'
DEFENDANT_DATA_NAV_ID = 'cdk-step-label-0-2'
FIRST_FORM_NAME_FIELD = 'mat-input-0'
FIRST_FORM_COMMITMENTS_FIELD = 'mat-input-1'
FIRST_FORM_MONEY_FIELD = 'mat-input-2'
SECOND_FORM_DEFENDANT_NAME = 'mat-input-3'
SECOND_FORM_DEFENDANT_FAULT = 'mat-input-4'
SECOND_FORM_DEFENDANT_DROPDOWN = 'mat-input-5'
SUMMARY_NAV_ID = 'cdk-step-label-0-3'
EXPECTED_TITLE = 'Docbuilder'
XPATH_DOWNLOAD_BUTTON = '//button[@class="mat-focus-indicator mat-raised-button mat-button-base mat-primary ng-star-inserted"]'
XPATH_CIRCLE = '//*[name()="circle" and contains(@class,"ng-star-in")]'
URL = 'https://test-ask.ridely.com/doc-wizard'
XPATH_INHERITANCE_BUTTON = '//div[@id="cdk-step-content-0-0"]//div[2]'